# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'z2a-expenses' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for z2a-expenses
  pod 'Firebase/Auth'  
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Google'
end
